/**
 * Clash Verge Rev / Clash JS Override Script
 * Converted from: 1.yaml
 */

function main(config) {
  // --- 1. 基础模板定义 ---
  var configAuto = {
    type: 'url-test',
    url: 'http://www.gstatic.com/generate_204',
    interval: 600,
    tolerance: 50,
    timeout: 5000,
    lazy: true,
    'expected-status': 204,
    hidden: true,
    'include-all': true,
  };

  var configFallback = {
    type: 'fallback',
    url: 'http://www.gstatic.com/generate_204',
    interval: 600,
    timeout: 3000,
    lazy: true,
    'expected-status': 204,
    hidden: true,
    'include-all': true,
  };

  var configLb = {
    type: 'load-balance',
    strategy: 'consistent-hashing',
    url: 'http://www.gstatic.com/generate_204',
    interval: 600,
    timeout: 5000,
    lazy: true,
    'expected-status': 204,
    hidden: true,
    'include-all': true,
  };

  var pStandard = {
    type: 'http',
    behavior: 'classical',
    format: 'yaml',
    interval: 86400,
  };

  // --- 2. 代理组配置 ---
  var proxyGroups = [
    { name: '手动切换', type: 'select', 'include-all': true, icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Static.png' },
    { name: 'Global', type: 'select', proxies: ['手动切换', 'DIRECT', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Global.png' },
    { name: 'ProxyDL', type: 'select', proxies: ['手动切换', 'DIRECT', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略', '低倍率策略', 'IPv6策略'], icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Global.png' },
    { name: 'FINAL', type: 'select', proxies: ['手动切换', 'DIRECT', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png' },
    { name: 'Claude', type: 'select', proxies: ['手动切换', 'IPv6策略', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/Claude_01.png' },
    { name: 'Google', type: 'select', proxies: ['手动切换', 'IPv6策略', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Google.png' },
    { name: 'Gemini', type: 'select', proxies: ['手动切换', 'IPv6策略', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/Gemini_01.png' },
    { name: 'AI', type: 'select', proxies: ['手动切换', 'IPv6策略', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/chatgpt(white1).png' },
    { name: 'Telegram', type: 'select', proxies: ['手动切换', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Telegram.png' },
    { name: 'YouTube', type: 'select', proxies: ['手动切换', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png' },
    { name: 'Twitter', type: 'select', proxies: ['手动切换', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Twitter.png' },
    { name: 'TikTok', type: 'select', proxies: ['手动切换', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/TikTok.png' },
    { name: 'Netflix', type: 'select', proxies: ['手动切换', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png' },
    { name: 'Bing', type: 'select', proxies: ['手动切换', 'DIRECT', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Bing.png' },
    { name: 'Apple', type: 'select', proxies: ['DIRECT', '手动切换', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png' },
    { name: 'Microsoft', type: 'select', proxies: ['手动切换', 'DIRECT', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Microsoft.png' },
    { name: 'Facebook', type: 'select', proxies: ['手动切换', '美国策略', '香港策略', '狮城策略', '台湾策略', '日本策略', '韩国策略', '欧洲策略'], icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Facebook.png' },
    
    { name: '时延优选', ...configAuto, hidden: false, icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png' },
    
    { name: '美国策略', type: 'select', proxies: ['美国-时延优选', '美国-故障转移', '美国-负载均衡'], 'include-all': true, filter: '美|US|(?i)States|American', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/US.png' },
    { name: '香港策略', type: 'select', proxies: ['香港-时延优选', '香港-故障转移', '香港-负载均衡'], 'include-all': true, filter: '港|HK|(?i)Hong', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/HK.png' },
    { name: '狮城策略', type: 'select', proxies: ['狮城-时延优选', '狮城-故障转移', '狮城-负载均衡'], 'include-all': true, filter: '新|坡|SG|(?i)Singapore', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/SG.png' },
    { name: '台湾策略', type: 'select', proxies: ['台湾-时延优选', '台湾-故障转移', '台湾-负载均衡'], 'include-all': true, filter: '台|湾|TW|(?i)Taiwan', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/TW.png' },
    { name: '日本策略', type: 'select', proxies: ['日本-时延优选', '日本-故障转移', '日本-负载均衡'], 'include-all': true, filter: '日|东京|JP|(?i)Japan', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/JP.png' },
    { name: '韩国策略', type: 'select', proxies: ['韩国-时延优选', '韩国-故障转移', '韩国-负载均衡'], 'include-all': true, filter: 'KR|韩国|韓|首尔|(?i)Korea', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/KR.png' },
    { name: '欧洲策略', type: 'select', proxies: ['欧洲-时延优选', '欧洲-故障转移', '欧洲-负载均衡'], 'include-all': true, filter: '🇬🇧|俄罗斯|🇷🇺|英国|法国|🇫🇷|德国|🇩🇪|瑞典|🇸🇪|西班牙|🇪🇸|伦敦|荷兰|🇳🇱|塞尔维亚|🇷🇸|挪威|丹麦|🇩🇰|🇳🇴|欧洲', icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/European_Union.png' },
    
    { name: 'IPv6策略', type: 'select', 'include-all': true, filter: '(?i)ipv6', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Nucleus.png' },
    { name: '低倍率策略', type: 'select', 'include-all': true, filter: '0\\.1|0\\.3|0\\.5|0\\.75', icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Download.png' },

    // 地区子分组
    { name: '美国-时延优选', ...configAuto, filter: '美|US|(?i)States|American', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png' },
    { name: '美国-故障转移', ...configFallback, filter: '美|US|(?i)States|American', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Available.png' },
    { name: '美国-负载均衡', ...configLb, filter: '美|US|(?i)States|American', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Round_Robin.png' },
    { name: '香港-时延优选', ...configAuto, filter: '港|HK|(?i)Hong', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png' },
    { name: '香港-故障转移', ...configFallback, filter: '港|HK|(?i)Hong', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Available.png' },
    { name: '香港-负载均衡', ...configLb, filter: '港|HK|(?i)Hong', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Round_Robin.png' },
    { name: '狮城-时延优选', ...configAuto, filter: '新|坡|SG|(?i)Singapore', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png' },
    { name: '狮城-故障转移', ...configFallback, filter: '新|坡|SG|(?i)Singapore', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Available.png' },
    { name: '狮城-负载均衡', ...configLb, filter: '新|坡|SG|(?i)Singapore', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Round_Robin.png' },
    { name: '日本-时延优选', ...configAuto, filter: '日|东京|JP|(?i)Japan', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png' },
    { name: '日本-故障转移', ...configFallback, filter: '日|东京|JP|(?i)Japan', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Available.png' },
    { name: '日本-负载均衡', ...configLb, filter: '日|东京|JP|(?i)Japan', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Round_Robin.png' },
    { name: '台湾-时延优选', ...configAuto, filter: '台|湾|TW|(?i)Taiwan', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png' },
    { name: '台湾-故障转移', ...configFallback, filter: '台|湾|TW|(?i)Taiwan', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Available.png' },
    { name: '台湾-负载均衡', ...configLb, filter: '台|湾|TW|(?i)Taiwan', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Round_Robin.png' },
    { name: '韩国-时延优选', ...configAuto, filter: 'KR|韩国|韓|首尔|(?i)Korea', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png' },
    { name: '韩国-故障转移', ...configFallback, filter: 'KR|韩国|韓|首尔|(?i)Korea', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Available.png' },
    { name: '韩国-负载均衡', ...configLb, filter: 'KR|韩国|韓|首尔|(?i)Korea', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Round_Robin.png' },
    { name: '欧洲-时延优选', ...configAuto, filter: '🇬🇧|俄罗斯|🇷🇺|英国|法国|🇫🇷|德国|🇩🇪|瑞典|🇸🇪|西班牙|🇪🇸|伦敦|荷兰|🇳🇱|塞尔维亚|🇷🇸|挪威|丹麦|🇩🇰|🇳🇴|欧洲', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Urltest.png' },
    { name: '欧洲-故障转移', ...configFallback, filter: '🇬🇧|俄罗斯|🇷🇺|英国|法国|🇫🇷|德国|🇩🇪|瑞典|🇸🇪|西班牙|🇪🇸|伦敦|荷兰|🇳🇱|塞尔维亚|🇷🇸|挪威|丹麦|🇩🇰|🇳🇴|欧洲', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Available.png' },
    { name: '欧洲-负载均衡', ...configLb, filter: '🇬🇧|俄罗斯|🇷🇺|英国|法国|🇫🇷|德国|🇩🇪|瑞典|🇸🇪|西班牙|🇪🇸|伦敦|荷兰|🇳🇱|塞尔维亚|🇷🇸|挪威|丹麦|🇩🇰|🇳🇴|欧洲', icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/Round_Robin.png' },
  ];

  // --- 3. 规则配置 ---
  var rules = [
    'GEOSITE,Category-ads-all,REJECT',
    'RULE-SET,AdBlock,REJECT,no-resolve',
    'RULE-SET,Hijacking,REJECT,no-resolve',
    'RULE-SET,Privacy,REJECT,no-resolve',
    'RULE-SET,BlockHttpDNS,REJECT,no-resolve',
    'GEOIP,lan,DIRECT,no-resolve',
    'GEOIP,private,DIRECT,no-resolve',
    'GEOSITE,private,DIRECT',
    'RULE-SET,PayPal,DIRECT',
    'RULE-SET,AmazonCN,DIRECT',
    'RULE-SET,Speedtest,DIRECT',
    'RULE-SET,WeChat,DIRECT',
    'RULE-SET,BiliBili,DIRECT',
    'RULE-SET,DouYin,DIRECT',
    'RULE-SET,Game,DIRECT,no-resolve',
    'RULE-SET,SteamCN,DIRECT',
    'RULE-SET,GameDownload,DIRECT',
    'RULE-SET,GameDownloadCN,DIRECT',
    'RULE-SET,PrivateTracker,DIRECT',
    'DOMAIN-KEYWORD,emby,手动切换',
    'RULE-SET,Imgur,Global',
    'RULE-SET,AppleDev,Global',
    'RULE-SET,AppleProxy,Global',
    'RULE-SET,iCloudPrivateRelay,Global',
    'RULE-SET,1Password,Global',
    'RULE-SET,Google,Google',
    'RULE-SET,Claude,Claude',
    'RULE-SET,Gemini,Gemini',
    'RULE-SET,AI,AI',
    'RULE-SET,GitHub,Global',
    'RULE-SET,Developer,Global',
    'RULE-SET,Spotify,Global',
    'RULE-SET,Twitch,Global',
    'RULE-SET,Notion,Global',
    'RULE-SET,Line,Global',
    'RULE-SET,Discord,Global',
    'RULE-SET,Whatsapp,Global',
    'RULE-SET,Bing,Bing',
    'RULE-SET,Twitter,Twitter',
    'RULE-SET,Telegram,Telegram,no-resolve',
    'RULE-SET,YouTube,YouTube,no-resolve',
    'RULE-SET,TikTok,TikTok',
    'RULE-SET,Netflix,Netflix',
    'RULE-SET,Dropbox,ProxyDL',
    'RULE-SET,OneDrive,ProxyDL',
    'RULE-SET,GoogleDrive,ProxyDL',
    'RULE-SET,PikPak,ProxyDL',
    'RULE-SET,TeraBox,ProxyDL',
    'RULE-SET,Amazon,Global',
    'RULE-SET,Apple,Apple',
    'RULE-SET,Microsoft,Microsoft',
    'RULE-SET,Facebook,Facebook',
    'RULE-SET,Proxy,Global,no-resolve',
    'RULE-SET,Global,Global,no-resolve',
    'RULE-SET,GlobalMedia,Global,no-resolve',
    'RULE-SET,Download,DIRECT',
    'GEOSITE,CN,DIRECT',
    'GEOIP,CN,DIRECT,no-resolve',
    'MATCH,FINAL',
  ];

  // --- 4. 规则集定义 (Rule Providers) ---
  var ruleProviders = {
    AdBlock: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_No_Resolve.yaml', path: './ruleset/Advertising.yaml' },
    Hijacking: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking_No_Resolve.yaml', path: './ruleset/Hijacking.yaml' },
    Privacy: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_No_Resolve.yaml', path: './ruleset/Privacy.yaml' },
    BlockHttpDNS: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS_No_Resolve.yaml', path: './ruleset/BlockHttpDNS.yaml' },
    PayPal: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PayPal/PayPal.yaml', path: './ruleset/PayPal.yaml' },
    AmazonCN: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonCN/AmazonCN.yaml', path: './ruleset/AmazonCN.yaml' },
    Speedtest: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Speedtest/Speedtest.yaml', path: './ruleset/Speedtest.yaml' },
    WeChat: { ...pStandard, url: 'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/WeChat/WeChat_No_Resolve.yaml', path: './ruleset/WeChat.yaml' },
    BiliBili: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili_No_Resolve.yaml', path: './ruleset/BiliBili.yaml' },
    DouYin: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin_No_Resolve.yaml', path: './ruleset/DouYin.yaml' },
    Game: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game_No_Resolve.yaml', path: './ruleset/Game.yaml' },
    SteamCN: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml', path: './ruleset/SteamCN.yaml' },
    GameDownload: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.yaml', path: './ruleset/GameDownload.yaml' },
    GameDownloadCN: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.yaml', path: './ruleset/GameDownloadCN.yaml' },
    PrivateTracker: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.yaml', path: './ruleset/PrivateTracker.yaml' },
    Imgur: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Imgur/Imgur.yaml', path: './ruleset/Imgur.yaml' },
    AppleDev: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleDev/AppleDev.yaml', path: './ruleset/AppleDev.yaml' },
    AppleProxy: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleProxy/AppleProxy.yaml', path: './ruleset/AppleProxy.yaml' },
    iCloudPrivateRelay: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iCloudPrivateRelay/iCloudPrivateRelay.yaml', path: './ruleset/iCloudPrivateRelay.yaml' },
    '1Password': { ...pStandard, url: 'https://raw.githubusercontent.com/C2dark/oxJS/refs/heads/dev/Clash/rules/1Password.yaml', path: './ruleset/1Password.yaml' },
    Claude: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.yaml', path: './ruleset/Claude.yaml' },
    Gemini: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.yaml', path: './ruleset/Gemini.yaml' },
    AI: { ...pStandard, url: 'https://raw.githubusercontent.com/C2dark/oxJS/refs/heads/dev/Clash/rules/AI.yaml', path: './ruleset/AI.yaml' },
    GitHub: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml', path: './ruleset/GitHub.yaml' },
    Developer: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Developer/Developer.yaml', path: './ruleset/Developer.yaml' },
    Spotify: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml', path: './ruleset/Spotify.yaml' },
    Twitch: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitch/Twitch.yaml', path: './ruleset/Twitch.yaml' },
    Notion: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Notion/Notion.yaml', path: './ruleset/Notion.yaml' },
    Line: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.yaml', path: './ruleset/Line.yaml' },
    Discord: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.yaml', path: './ruleset/Discord.yaml' },
    Whatsapp: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Whatsapp/Whatsapp.yaml', path: './ruleset/Whatsapp.yaml' },
    Bing: { ...pStandard, url: 'https://rule.kelee.one/Clash/Bing.yaml', path: './ruleset/Bing.yaml' },
    Twitter: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml', path: './ruleset/Twitter.yaml' },
    Telegram: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml', path: './ruleset/Telegram.yaml' },
    YouTube: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube_No_Resolve.yaml', path: './ruleset/YouTube.yaml' },
    TikTok: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.yaml', path: './ruleset/TikTok.yaml' },
    Netflix: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.yaml', path: './ruleset/Netflix.yaml' },
    Dropbox: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Dropbox/Dropbox.yaml', path: './ruleset/Dropbox.yaml' },
    OneDrive: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml', path: './ruleset/OneDrive.yaml' },
    GoogleDrive: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleDrive/GoogleDrive.yaml', path: './ruleset/GoogleDrive.yaml' },
    PikPak: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PikPak/PikPak.yaml', path: './ruleset/PikPak.yaml' },
    TeraBox: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TeraBox/TeraBox.yaml', path: './ruleset/TeraBox.yaml' },
    Amazon: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon.yaml', path: './ruleset/Amazon.yaml' },
    Apple: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Classical.yaml', path: './ruleset/Apple.yaml' },
    Google: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml', path: './ruleset/Google.yaml' },
    Microsoft: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml', path: './ruleset/Microsoft.yaml' },
    Facebook: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.yaml', path: './ruleset/Facebook.yaml' },
    Proxy: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Proxy/Proxy_No_Resolve.yaml', path: './ruleset/Proxy.yaml' },
    Global: { ...pStandard, url: 'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Global/Global_No_Resolve.yaml', path: './ruleset/Global.yaml' },
    GlobalMedia: { ...pStandard, url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_No_Resolve.yaml', path: './ruleset/GlobalMedia.yaml' },
    Download: { ...pStandard, url: 'https://raw.githubusercontent.com/C2dark/oxJS/refs/heads/dev/Clash/rules/Download.yaml', path: './ruleset/Download.yaml' },
  };

  // --- 5. 执行合并 ---
  return {
    ...config,
    'proxy-groups': proxyGroups,
    'rule-providers': ruleProviders,
    rules: rules,
  };
}